name: Test & Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: build
    strategy:
      matrix:
        go: ['1.20']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - uses: actions/checkout@v3
      - name: Run 'go test'
        run: go test -race -count=1 ./...
      - name: Run 'go build'
        run: go build -race cmd/mclogs/*.go

  golangci:
    name: lint
    strategy:
      matrix:
        go: ['1.20']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          args: --timeout 5m
